server:
  port: 80
  session:
    timeout: 30
    #ssl:
    key-store: classpath:keystore.p12
    key-store-password: 161231
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiangfengtea?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 161231
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  redis:
    host: localhost
    port: 6379
    max-wait: 30000
    max-active: 100
    max-idle: 20
    min-idle: 0
    timeout: 3000
  mail:
    host: smtp.qq.com
    username: 1193013640@qq.com
    password: ujmbjdweckegggaj
    default-encoding: UTF-8
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,file:${imageLocation}

mail:
  fromMail:
    addr: 1193013640@qq.com
  verifyCodeTimeout: 60
cookie:
  max-age: 7776000
token:
  redisSaveTime: 3600
address:
  receiveAddress:
    topLimit: 20

upload:
  image:
    userHead:
      absolute: ${imageLocation}/images/user/
      relative: /images/user/

imageLocation: D:/xiangfengtea
